# Generated by Django 3.0.5 on 2020-04-09 16:42

from django.db import migrations, models
import listing.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200409_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=listing.models.listing_upload_path),
        ),
    ]
