# Generated by Django 3.0.5 on 2020-04-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200410_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='city',
        ),
        migrations.RemoveField(
            model_name='category',
            name='country',
        ),
        migrations.RemoveField(
            model_name='category',
            name='region',
        ),
    ]
