# Generated by Django 3.0.5 on 2020-04-09 16:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20200409_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
