# Generated by Django 3.0.5 on 2020-04-10 21:05

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('listing', '0003_auto_20200410_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos1', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos2', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo3',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos3', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
