# Generated by Django 3.0.5 on 2020-04-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200410_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
