# Generated by Django 3.0.5 on 2020-04-09 17:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20200409_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
