# Generated by Django 3.0.5 on 2020-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listing_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.TextField(blank=True),
        ),
    ]
