# Generated by Django 3.0.5 on 2020-04-11 05:12

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('listing', '0006_auto_20200410_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photofeatured',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photosfeatured', to=settings.FILER_IMAGE_MODEL, verbose_name='Featured Image'),
        ),
    ]
